program: train.py
backbone: resnet18
dataset: shape
data_dir: data/
output_dir: ./weights
# checkpoint:

batch_size: 1
save_every: 50
epochs: 100

epsilon: 0
lr: 0.01
lr_decay: step
lr_decay_epochs: 33,66
n_views: 2
